package com.bawei.demo0102.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.demo0102.BannerInfoEntity;
import com.bawei.demo0102.ProductInfoEntity;

import com.bawei.demo0102.greendao.BannerInfoEntityDao;
import com.bawei.demo0102.greendao.ProductInfoEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bannerInfoEntityDaoConfig;
    private final DaoConfig productInfoEntityDaoConfig;

    private final BannerInfoEntityDao bannerInfoEntityDao;
    private final ProductInfoEntityDao productInfoEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bannerInfoEntityDaoConfig = daoConfigMap.get(BannerInfoEntityDao.class).clone();
        bannerInfoEntityDaoConfig.initIdentityScope(type);

        productInfoEntityDaoConfig = daoConfigMap.get(ProductInfoEntityDao.class).clone();
        productInfoEntityDaoConfig.initIdentityScope(type);

        bannerInfoEntityDao = new BannerInfoEntityDao(bannerInfoEntityDaoConfig, this);
        productInfoEntityDao = new ProductInfoEntityDao(productInfoEntityDaoConfig, this);

        registerDao(BannerInfoEntity.class, bannerInfoEntityDao);
        registerDao(ProductInfoEntity.class, productInfoEntityDao);
    }
    
    public void clear() {
        bannerInfoEntityDaoConfig.clearIdentityScope();
        productInfoEntityDaoConfig.clearIdentityScope();
    }

    public BannerInfoEntityDao getBannerInfoEntityDao() {
        return bannerInfoEntityDao;
    }

    public ProductInfoEntityDao getProductInfoEntityDao() {
        return productInfoEntityDao;
    }

}
